name: "on-push-check-and-publish-package"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Check & Publish utils package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/utils/package.json"